name: Deploy Snippets on Push

on:
  push:
    branches:
    - main
  release:
    types:
    - created
  repository_dispatch:
    types: [upload_products]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Python3
      uses: actions/setup-python@v5
      with: 
        python-version: '3.10' 


    - name: Install dependencies
      run: pip install -r requirements.txt && playwright install
      
 
   
      
    - name: Upload Products
      run: cd pipeline/daraz && python crawlProducts.py
      env:
        TOKEN: ${{ secrets.TOKEN }}
    
